# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cannula', '0021_auto_20190116_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='AMTSL_D',
            new_name='amtsl_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='AMTSL_N',
            new_name='amtsl_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Asphyxia_D',
            new_name='asphyxia_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Asphyxia_N',
            new_name='asphyxia_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DDepoProvera',
            new_name='ddepoprovera',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DEpills',
            new_name='depills',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DFcondoms',
            new_name='dfcondoms',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Diarrhea_D',
            new_name='diarrhea_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Diarrhea_N',
            new_name='diarrhea_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DImplanon',
            new_name='dimplanon',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DIUD',
            new_name='diud',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DJadelle',
            new_name='djadelle',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DMbeads',
            new_name='dmbeads',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DMcondoms',
            new_name='dmcondoms',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DPills',
            new_name='dpills',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='DSayana',
            new_name='dsayana',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='HEI_D',
            new_name='hei_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='HEI_N',
            new_name='hei_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='IPT2_D',
            new_name='ipt2_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='IPT2_N',
            new_name='ipt2_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Pneumonia_D',
            new_name='pneumonia_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Pneumonia_N',
            new_name='pneumonia_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Ret_D',
            new_name='ret_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='Ret_N',
            new_name='ret_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='severe_malaria_D',
            new_name='severe_malaria_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='severe_malaria_N',
            new_name='severe_malaria_n',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='simple_malaria_D',
            new_name='simple_malaria_d',
        ),
        migrations.RenameField(
            model_name='rmnchandmalaria',
            old_name='simple_malaria_N',
            new_name='simple_malaria_n',
        ),
    ]
