from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'dashboards/malaria/$', views.index, name='thematic_malaria'),
    url(r'dashboards/malaria/compliance\.php', views.malaria_compliance, name='malaria_compliance'),
    url(r'dashboards/malaria/quarterly\.php', views.ipt_quarterly, name='ipt_quarterly'),
    url(r'dashboards/malaria/quarterly\.xls', views.ipt_quarterly, {'output_format': 'EXCEL'}, name='ipt_quarterly_excel'),
    url(r'validation_rule\.php', views.validation_rule, name='validation_rule'),
    url(r'data_workflow_new\.php/(?P<menu_name>.*)/$', views.data_workflow_new, name='data_workflow_new'),
    url(r'validation_rule\.xls', views.validation_rule, {'output_format': 'EXCEL'}, name='validation_rule_excel'),
    url(r'data_workflow\.php', views.data_workflow_detail, name='data_workflow_detail'),
    url(r'data_workflows\.php', views.data_workflow_listing, name='data_workflow_listing'),
    url(r'data_element_alias\.php', views.data_element_alias, name='data_element_alias'),
    url(r'dashboards/hts/$', views.index, name='thematic_hts'),
    url(r'dashboards/hts/sites\.php', views.hts_by_site, name='hts_sites'),
    url(r'dashboards/hts/sites\.xls', views.hts_by_site, {'output_format': 'EXCEL'}, name='hts_sites_excel'),
    url(r'dashboards/hts/districts\.php', views.hts_by_district, name='hts_districts'),
    url(r'dashboards/hts/districts\.xls', views.hts_by_district, {'output_format': 'EXCEL'}, name='hts_districts_excel'),
    url(r'dashboards/vl/sites\.php', views.vl_by_site, name='vl_sites'),
    url(r'dashboards/vl/sites\.xls', views.vl_by_site, {'output_format': 'EXCEL'}, name='vl_sites_excel'),
    url(r'dashboards/vmmc/$', views.index, name='thematic_vmmc'),
    url(r'dashboards/vmmc/sites\.php', views.vmmc_by_site, name='vmmc_sites'),
    url(r'dashboards/vmmc/sites\.xls', views.vmmc_by_site, {'output_format': 'EXCEL'}, name='vmmc_sites_excel'),
    url(r'dashboards/lab/$', views.index, name='thematic_lab'),
    url(r'dashboards/lab/sites\.php', views.lab_by_site, name='lab_sites'),
    url(r'dashboards/lab/sites\.xls', views.lab_by_site, {'output_format': 'EXCEL'}, name='lab_sites_excel'),
    url(r'dashboards/fp/$', views.index, name='thematic_fp'),
    url(r'dashboards/fp/sites\.php', views.fp_by_site, name='fp_sites'),
    url(r'dashboards/fp/sites\.xls', views.fp_by_site, {'output_format': 'EXCEL'}, name='fp_sites_excel'),
    url(r'dashboards/fp/cyp_sites\.php', views.fp_cyp_by_site, name='fp_cyp_sites'),
    url(r'dashboards/fp/cyp_sites\.xls', views.fp_cyp_by_site, {'output_format': 'EXCEL'}, name='fp_cyp_sites_excel'),
    url(r'dashboards/fp/cyp_districts\.php', views.fp_cyp_by_district, name='fp_cyp_districts'),
    url(r'dashboards/fp/cyp_districts\.xls', views.fp_cyp_by_district, {'output_format': 'EXCEL'}, name='fp_cyp_districts_excel'),
    url(r'dashboards/nutrition/$', views.index, name='thematic_nutrition'),
    url(r'dashboards/nutrition/hospitals\.php', views.nutrition_by_hospital, name='nutrition_hospitals'),
    url(r'dashboards/nutrition/hospitals\.xls', views.nutrition_by_hospital, {'output_format': 'EXCEL'}, name='nutrition_hospitals_excel'),
]
